PLUGINNAME=recaptcha-phpbb
VERSION=1.6

DESCRIPTION="reCAPTCHA Plugin for phpBB - v$(VERSION)"

FILES =						\
	profile_add_body.tpl.patch		\
	usercp_register.patch			\
	README

COPYFILES =					\
	../php/recaptchalib.php

include ../Makefile.frag
