PLUGINNAME=recaptcha-mediawiki
VERSION=1.6

DESCRIPTION="reCAPTCHA Plugin for MediaWiki - v$(VERSION)"


FILES =						\
	AUTHORS					\
	ConfirmEdit.i18n.php			\
	ConfirmEdit.php				\
	README					\
	ReCaptcha.i18n.php			\
	ReCaptcha.php

COPYFILES =					\
	../php/recaptchalib.php

include ../Makefile.frag
