PLUGINNAME=recaptcha-wordpress
VERSION=1.4

DESCRIPTION="reCAPTCHA Plugin for WordPress - v$(VERSION)"

FILES  =					\
	comments.patch				\
	LICENSE					\
	README					\
	recaptcha.php

COPYFILES =					\
	../php/recaptchalib.php

include ../Makefile.frag
